import assert from 'assert';
import crypto from 'crypto';
import { prisma } from '../config/prisma.js';

const BASE_URL = 'http://localhost:5000/api/v1';

async function runStartupRegistrationAndVerificationTests() {
  console.log('===============================================================');
  console.log('🚀 RUNNING GeM-STYLE STARTUP REGISTRATION & VERIFICATION TEST SUITE');
  console.log('===============================================================');

  const uniqueSuffix = Date.now();
  const testEmail = `founder_${uniqueSuffix}@techstart.in`;
  const weakPassword = 'Short1!';
  const strongPassword = 'StrongPassword123!@#';

  let rawVerificationToken = null;
  let authToken = null;
  let testUserId = null;
  let testStartupId = null;

  // -------------------------------------------------------------------------
  // TEST 1: Password validation policy (12+ characters required)
  // -------------------------------------------------------------------------
  console.log('\n--- TEST 1: Password Validation Policy Enforcement ---');
  const weakPassRes = await fetch(`${BASE_URL}/auth/register`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name: 'Vikas Test Founder',
      email: testEmail,
      password: weakPassword,
      company_name: `TechCorp_${uniqueSuffix}`,
    }),
  });
  const weakPassData = await weakPassRes.json();
  assert.strictEqual(weakPassRes.status, 422, 'Weak password should be rejected with 422');
  console.log('✅ Weak password rejected (requires 12+ chars):', weakPassData.message);

  // -------------------------------------------------------------------------
  // TEST 2: Successful Registration creates Inactive User and Draft Startup
  // -------------------------------------------------------------------------
  console.log('\n--- TEST 2: Public Registration creates Inactive User & Draft Startup ---');
  const regRes = await fetch(`${BASE_URL}/auth/register`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name: 'Vikas Test Founder',
      email: testEmail,
      password: strongPassword,
      company_name: `TechCorp Innovations ${uniqueSuffix}`,
      phone: '9876543210',
    }),
  });
  const regData = await regRes.json();
  assert.strictEqual(regRes.status, 201, 'Registration must return 201 Created');
  assert.strictEqual(regData.data.user.is_active, false, 'User must be initially inactive');
  assert.strictEqual(regData.data.user.is_verified, false, 'User must be unverified before email confirmation');
  assert.strictEqual(regData.data.email_verification_required, true, 'Email verification flag must be set');
  
  testUserId = regData.data.user.id;
  testStartupId = regData.data.startup_id;
  console.log('✅ Registered unverified user & draft startup:', { userId: testUserId, startupId: testStartupId });

  // -------------------------------------------------------------------------
  // TEST 3: Unverified User cannot login
  // -------------------------------------------------------------------------
  console.log('\n--- TEST 3: Login blocked for unverified email accounts ---');
  const unverifiedLoginRes = await fetch(`${BASE_URL}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      email: testEmail,
      password: strongPassword,
    }),
  });
  const unverifiedLoginData = await unverifiedLoginRes.json();
  assert.strictEqual(unverifiedLoginRes.status, 401, 'Unverified user login must return 401');
  console.log('✅ Login prevented for unverified account:', unverifiedLoginData.message);

  // -------------------------------------------------------------------------
  // TEST 4: Email Verification Token Hash Validation & Activation
  // -------------------------------------------------------------------------
  console.log('\n--- TEST 4: Email Verification Token Resolution & Account Activation ---');
  // Retrieve token hash directly from DB to simulate the email link delivered to user
  const dbUser = await prisma.user.findUnique({ where: { id: testUserId } });
  assert(dbUser.email_verification_token_hash, 'Token hash must be stored in database');
  
  // Test invalid token
  const invalidVerifyRes = await fetch(`${BASE_URL}/auth/verify-email`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ token: 'invalid_fake_token_12345' }),
  });
  assert.strictEqual(invalidVerifyRes.status, 400, 'Invalid token must return 400 Bad Request');
  console.log('✅ Fake/Invalid email verification token safely rejected');

  // Verify using an active token generated by the service
  // In development, the raw token is securely generated during authService.register. We can trigger resend or update hash.
  const testRawToken = crypto.randomBytes(32).toString('hex');
  const testTokenHash = crypto.createHash('sha256').update(testRawToken).digest('hex');
  await prisma.user.update({
    where: { id: testUserId },
    data: {
      email_verification_token_hash: testTokenHash,
      email_verification_expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000),
    },
  });

  const validVerifyRes = await fetch(`${BASE_URL}/auth/verify-email`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ token: testRawToken }),
  });
  const validVerifyData = await validVerifyRes.json();
  assert.strictEqual(validVerifyRes.status, 200, 'Valid token verification must succeed');
  assert(validVerifyData.data.token, 'Token verification must return JWT auth token');
  assert.strictEqual(validVerifyData.data.user.is_verified, true, 'User is_verified must now be true');
  assert.strictEqual(validVerifyData.data.user.is_active, true, 'User is_active must now be true');

  authToken = validVerifyData.data.token;
  console.log('✅ Email verified and session activated. JWT Token obtained.');

  // -------------------------------------------------------------------------
  // TEST 5: Multi-Step Draft Updates (Constitution, Address, Rep, Statutory IDs)
  // -------------------------------------------------------------------------
  console.log('\n--- TEST 5: GeM-Style Multi-Step Registration Draft Saves ---');
  
  // Step 2 & 3: Organization Details & Authorized Signatory
  const patchRes1 = await fetch(`${BASE_URL}/startups/registration/${testStartupId}`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    },
    body: JSON.stringify({
      org_type: 'PRIVATE_LIMITED',
      address_line1: '101, Tech Park, Cyber City',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      country: 'India',
      authorized_person_name: 'Vikas Test Founder',
      authorized_person_designation: 'Director & CEO',
      authorized_person_email: testEmail,
      authorized_person_phone: '9876543210',
      authorization_type: 'BOARD_RESOLUTION',
    }),
  });
  const patchData1 = await patchRes1.json();
  assert.strictEqual(patchRes1.status, 200, 'Draft update must succeed');
  assert.strictEqual(patchData1.data.startup.org_type, 'PRIVATE_LIMITED');
  assert.strictEqual(patchData1.data.startup.city, 'Bengaluru');
  console.log('✅ Saved Organization Constitution & Signatory details');

  // Step 4 & 5: Business Identifiers (PAN, GSTIN, CIN, DPIIT) & Profile
  const patchRes2 = await fetch(`${BASE_URL}/startups/registration/${testStartupId}`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    },
    body: JSON.stringify({
      pan_number: 'AAACT2718E',
      gstin: '29AAACT2718E1Z5',
      cin_number: 'U72200KA2024PTC123456',
      dpiit_number: 'DIPP98765',
      domain: 'HealthTech',
      trl: 7,
      description: 'AI-driven hospital workflow optimization platform for Ayushman Bharat.',
    }),
  });
  const patchData2 = await patchRes2.json();
  assert.strictEqual(patchRes2.status, 200, 'Business identifiers draft update must succeed');
  assert.strictEqual(patchData2.data.startup.pan_number, 'AAACT2718E');
  assert.strictEqual(patchData2.data.startup.dpiit_number, 'DIPP98765');
  console.log('✅ Saved PAN, GSTIN, CIN, DPIIT & Technology Profile');

  // -------------------------------------------------------------------------
  // TEST 6: Sensitive Bank Details Upsert & API Sanitization
  // -------------------------------------------------------------------------
  console.log('\n--- TEST 6: Sensitive Bank Details Storage & Protection ---');
  const bankRes = await fetch(`${BASE_URL}/startups/registration/${testStartupId}/bank-details`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    },
    body: JSON.stringify({
      account_holder_name: 'TechCorp Innovations Private Limited',
      bank_name: 'State Bank of India',
      account_number: '309988776655',
      ifsc_code: 'SBIN0001234',
      branch_name: 'Cyber City Branch',
      account_type: 'CURRENT',
    }),
  });
  const bankData = await bankRes.json();
  assert.strictEqual(bankRes.status, 200, 'Bank details upsert must succeed');
  assert.strictEqual(bankData.data.bank_details.bank_name, 'State Bank of India');
  console.log('✅ Sensitive bank details successfully saved');

  // Login as Government Officer to verify external access does NOT expose sensitive bank details
  const govtLoginRes = await fetch(`${BASE_URL}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: 'ramesh.kumar@health.gov.in', password: 'Password123!' }),
  });
  const govtData = await govtLoginRes.json();
  const govtToken = govtData?.data?.token;

  // Verify external GET /startups/:id does NOT expose sensitive bank details
  const publicStartupRes = await fetch(`${BASE_URL}/startups/${testStartupId}`, {
    headers: { Authorization: `Bearer ${govtToken}` },
  });
  const publicStartupData = await publicStartupRes.json();
  assert.strictEqual(publicStartupRes.status, 200, 'External GET /startups/:id should succeed');
  assert.strictEqual(publicStartupData.data.startup.bank_details, undefined, 'External GET /startups/:id must never expose bank details');
  console.log('✅ External role correctly sanitizes bank details');

  // -------------------------------------------------------------------------
  // TEST 7: Document Upload to Startup Registration
  // -------------------------------------------------------------------------
  console.log('\n--- TEST 7: Verification Documents Checklist Upload ---');
  const docRes1 = await fetch(`${BASE_URL}/startups/registration/${testStartupId}/documents`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    },
    body: JSON.stringify({
      document_type: 'COMPANY_PAN',
      document_url: 'https://setugov.in/docs/pan_sample.pdf',
      file_name: 'PAN_Card.pdf',
      file_size: 204800,
      mime_type: 'application/pdf',
    }),
  });
  const docData1 = await docRes1.json();
  assert.strictEqual(docRes1.status, 201, 'Document upload must return 201');
  const docId = docData1.data.document.id;
  console.log('✅ Verification document uploaded (PAN):', docId);

  // Upload DPIIT certificate
  await fetch(`${BASE_URL}/startups/registration/${testStartupId}/documents`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    },
    body: JSON.stringify({
      document_type: 'DPIIT_CERTIFICATE',
      document_url: 'https://setugov.in/docs/dpiit_sample.pdf',
      file_name: 'DPIIT_Recognition.pdf',
      file_size: 154200,
      mime_type: 'application/pdf',
    }),
  });
  console.log('✅ Verification document uploaded (DPIIT Certificate)');

  // -------------------------------------------------------------------------
  // TEST 8: Registration Submission Completeness Validation
  // -------------------------------------------------------------------------
  console.log('\n--- TEST 8: Submission Completeness Validation ---');
  
  // Submit valid registration
  const submitRes = await fetch(`${BASE_URL}/startups/registration/${testStartupId}/submit`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    },
    body: JSON.stringify({
      declaration_accepted: true,
    }),
  });
  const submitData = await submitRes.json();
  if (submitRes.status !== 200) {
    console.error('Submit failure response:', submitData);
  }
  assert.strictEqual(submitRes.status, 200, 'Valid submission must succeed');
  assert.strictEqual(submitData.data.startup.verification_status, 'SUBMITTED', 'Status must transition to SUBMITTED');
  console.log('✅ Startup successfully submitted dossier for verification');

  // -------------------------------------------------------------------------
  // TEST 9: Admin Verification Dossier Inspection & Document Approval
  // -------------------------------------------------------------------------
  console.log('\n--- TEST 9: Admin Verification Dossier Review & Actions ---');
  
  // Login as Admin
  const adminLoginRes = await fetch(`${BASE_URL}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: 'admin@setugov.in', password: 'Password123!' }),
  });
  const adminData = await adminLoginRes.json();
  const adminToken = adminData?.data?.token;
  assert(adminToken, 'Admin token must be obtained');

  // Admin gets startup dossier
  const dossierRes = await fetch(`${BASE_URL}/admin/startup-verifications/${testStartupId}`, {
    headers: { Authorization: `Bearer ${adminToken}` },
  });
  const dossierData = await dossierRes.json();
  assert.strictEqual(dossierRes.status, 200, 'Admin can view full startup dossier');
  assert(dossierData.data.startup.bank_details, 'Admin can view sensitive bank details for verification');
  assert.strictEqual(dossierData.data.startup.documents.length, 2, 'Admin can view all uploaded documents');
  console.log('✅ Admin successfully inspected full seller dossier & bank details');

  // Admin moves status to UNDER_REVIEW
  const reviewRes = await fetch(`${BASE_URL}/admin/startup-verifications/${testStartupId}`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${adminToken}`,
    },
    body: JSON.stringify({ action: 'START_REVIEW' }),
  });
  const reviewData = await reviewRes.json();
  assert.strictEqual(reviewData.data.startup.verification_status, 'UNDER_REVIEW');
  console.log('✅ Admin marked dossier as UNDER_REVIEW');

  // Admin verifies individual document
  const verifyDocRes = await fetch(`${BASE_URL}/admin/startup-documents/${docId}/verification`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${adminToken}`,
    },
    body: JSON.stringify({
      verification_status: 'VERIFIED',
    }),
  });
  assert.strictEqual(verifyDocRes.status, 200, 'Admin document verification must succeed');
  console.log('✅ Admin verified individual document');

  // Admin triggers CORRECTION_REQUESTED
  const correctionRes = await fetch(`${BASE_URL}/admin/startup-verifications/${testStartupId}`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${adminToken}`,
    },
    body: JSON.stringify({
      action: 'REQUEST_CORRECTION',
      correction_notes: 'Please verify that the IFSC code corresponds to the active corporate account branch.',
    }),
  });
  const correctionData = await correctionRes.json();
  assert.strictEqual(correctionData.data.startup.verification_status, 'CORRECTION_REQUESTED');
  console.log('✅ Admin requested corrections from seller:', correctionData.data.startup.correction_notes);

  // Admin approves startup registration (Final Verification)
  const approveRes = await fetch(`${BASE_URL}/admin/startup-verifications/${testStartupId}`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${adminToken}`,
    },
    body: JSON.stringify({
      action: 'APPROVE',
      notes: 'All statutory records and bank details verified against MCA and DPIIT portal.',
    }),
  });
  const approveData = await approveRes.json();
  assert.strictEqual(approveRes.status, 200);
  assert.strictEqual(approveData.data.startup.verification_status, 'VERIFIED');
  console.log('✅ Admin approved startup. Status is now VERIFIED!');

  // -------------------------------------------------------------------------
  // TEST 10: Cleanup Test Artifacts
  // -------------------------------------------------------------------------
  console.log('\n--- CLEANUP: Removing Test Records ---');
  try {
    await prisma.startupBankDetails.deleteMany({ where: { startup_id: testStartupId } });
    await prisma.startupDocument.deleteMany({ where: { startup_id: testStartupId } });
    await prisma.startup.deleteMany({ where: { id: testStartupId } });
    await prisma.user.deleteMany({ where: { id: testUserId } });
    console.log('✅ Test startup and user successfully cleaned up');
  } catch (cleanErr) {
    console.warn('⚠️ Cleanup note:', cleanErr.message);
  }

  console.log('\n===============================================================');
  console.log('🎉 ALL GeM-STYLE REGISTRATION & VERIFICATION TESTS PASSED!');
  console.log('===============================================================');
}

runStartupRegistrationAndVerificationTests()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('\n❌ TEST SUITE FAILED:', err);
    process.exit(1);
  });
