import { prisma } from '../config/prisma.js';
import { config } from '../config/env.js';
import { logger } from '../utils/logger.js';
import { NotFoundError } from '../utils/errors.js';

/**
 * Helper to execute HTTP request to Python / Ollama AI service with fallback
 */
const callExternalAiService = async (endpoint, payload) => {
  if (config.AI_MOCK_MODE) {
    return null; // Force mock fallback
  }

  try {
    const url = `${config.AI_SERVICE_URL}${endpoint}`;
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(10000) // 10s timeout
    });

    if (response.ok) {
      return await response.json();
    }
    logger.warn(`AI service returned non-200 status: ${response.status}. Falling back to mock generator.`);
  } catch (error) {
    logger.warn(`AI service at ${config.AI_SERVICE_URL} unavailable (${error.message}). Using local AI heuristics.`);
  }
  return null;
};

/**
 * Generate Structured Challenge Proposal from high-level problem statement
 */
export const generateChallenge = async (input) => {
  const { problem_statement, department_name, state, budget_range } = input;

  const externalResult = await callExternalAiService('/api/challenges/generate', input);
  if (externalResult) return externalResult;

  // Mock / Heuristic AI generation
  const cleanStatement = problem_statement || 'Public Service Efficiency Optimization';
  
  return {
    generated_draft: {
      title: `${cleanStatement.split(' ').slice(0, 6).join(' ')} Innovation Challenge`,
      problem_description: `Current operational constraints in ${department_name || 'the department'} (${state || 'State'}) result in severe bottlenecks. ${cleanStatement}`,
      current_baseline: 'Manual process latency causing an estimated 40% operational delay and high administrative overhead.',
      desired_outcome: 'Deploy a field-tested automated platform delivering >= 35% reduction in turnaround time with end-to-end data auditability.',
      location: `${state || 'Central'} District Headquarters`,
      suggested_budget_min: 250000,
      suggested_budget_max: 500000,
      pilot_duration_days: 60,
      recommended_technologies: ['AI / ML', 'Predictive Analytics', 'Cloud API', 'Mobile Interface', 'Automated Workflow Engine'],
      evaluation_criteria: [
        { criterion: 'Technical Feasibility', weight: 25 },
        { criterion: 'Innovation', weight: 20 },
        { criterion: 'Expected Impact', weight: 25 },
        { criterion: 'Scalability', weight: 15 },
        { criterion: 'Cost Effectiveness', weight: 15 }
      ]
    },
    ai_metadata: {
      model: 'SetuGov-GovTech-Llama-Heuristic',
      mode: 'mock',
      disclaimer: 'This draft is generated by AI as a starting recommendation. Government officials must review, edit, and approve before publishing.'
    }
  };
};

/**
 * Analyze Government Challenge for completeness, clarity, and tech readiness
 */
export const analyzeChallenge = async (challengeId) => {
  const challenge = await prisma.challenge.findUnique({
    where: { id: challengeId },
    include: {
      department: true,
      applications: true,
      match_scores: true
    }
  });

  if (!challenge) {
    throw new NotFoundError(`Challenge with ID ${challengeId} not found.`);
  }

  const externalResult = await callExternalAiService(`/api/challenges/${challengeId}/analyze`, { challenge });
  if (externalResult) return externalResult;

  // Heuristic analysis
  const clarityScore = challenge.problem_description.length > 50 ? 92 : 70;
  const techSpecificity = challenge.required_technologies.length >= 3 ? 95 : 65;
  const budgetReasonableness = challenge.budget_max >= challenge.budget_min * 1.5 ? 90 : 75;
  const overallReadinessScore = Math.round((clarityScore + techSpecificity + budgetReasonableness) / 3);

  return {
    challenge_id: challengeId,
    title: challenge.title,
    readiness_assessment: {
      overall_readiness_score: overallReadinessScore,
      problem_clarity_score: clarityScore,
      technical_specificity_score: techSpecificity,
      budget_feasibility_score: budgetReasonableness
    },
    key_strengths: [
      'Well-defined baseline vs desired outcome metrics.',
      'Appropriate pilot duration for field validation.',
      'Clear technological domains specified.'
    ],
    recommended_improvements: [
      'Consider specifying interoperability standards (e.g., ABDM, NDOH, ONDC protocols).',
      'Define data privacy and local storage compliance requirements.'
    ],
    market_readiness_insight: 'High startup ecosystem density in this technology cluster. Expected 5-10 qualified applications.',
    ai_metadata: {
      model: 'SetuGov-GovTech-Analysis',
      mode: 'mock'
    }
  };
};

/**
 * Analyze Pilot Performance & Generate Scale / Extend / Stop recommendation
 */
export const analyzePilot = async (pilotId) => {
  const pilot = await prisma.pilot.findUnique({
    where: { id: pilotId },
    include: {
      challenge: { include: { department: true } },
      startup: true,
      kpis: { include: { measurements: true } },
      milestones: true,
      evidence: true,
      risks: true,
      validations: true
    }
  });

  if (!pilot) {
    throw new NotFoundError(`Pilot with ID ${pilotId} not found.`);
  }

  const externalResult = await callExternalAiService(`/api/pilots/${pilotId}/analyze`, { pilot });
  if (externalResult) return externalResult;

  // 1. Calculate KPI Achievement Average
  let totalKpiAchievement = 0;
  pilot.kpis.forEach(kpi => {
    if (kpi.actual_value !== null && kpi.actual_value !== undefined) {
      const isReduction = kpi.target_value < kpi.baseline_value;
      let ach = 0;
      if (isReduction) {
        ach = (kpi.baseline_value - kpi.actual_value) / (kpi.baseline_value - kpi.target_value);
      } else {
        ach = (kpi.actual_value - kpi.baseline_value) / (kpi.target_value - kpi.baseline_value);
      }
      totalKpiAchievement += Math.max(0, ach * 100);
    }
  });
  const avgKpiScore = pilot.kpis.length > 0 ? Math.round(totalKpiAchievement / pilot.kpis.length) : 85;

  // 2. Milestone completion
  const totalMilestones = pilot.milestones.length;
  const completedMilestones = pilot.milestones.filter(m => m.status === 'COMPLETED' || m.completion_percentage === 100).length;
  const milestoneScore = totalMilestones > 0 ? Math.round((completedMilestones / totalMilestones) * 100) : 90;

  // 3. Evidence quality & Risk exposure
  const verifiedEvidence = pilot.evidence.filter(e => e.verification_status === 'VERIFIED').length;
  const criticalRisks = pilot.risks.filter(r => (r.severity === 'CRITICAL' || r.severity === 'HIGH') && r.status === 'IDENTIFIED').length;

  // 4. Recommendation calculation
  let recommendedDecision = 'SCALE';
  let confidenceScore = 92;
  let summaryReasoning = '';

  if (avgKpiScore >= 90 && criticalRisks === 0) {
    recommendedDecision = 'SCALE';
    confidenceScore = 94;
    summaryReasoning = `Outstanding pilot performance: KPI target achievement average is ${avgKpiScore}%. All milestones delivered and verified with robust evidence. Critical risks are fully mitigated. Ready for statewide departmental scale-up.`;
  } else if (avgKpiScore >= 70 || (avgKpiScore < 90 && criticalRisks <= 1)) {
    recommendedDecision = 'EXTEND';
    confidenceScore = 82;
    summaryReasoning = `Promising pilot progress: KPI achievement is ${avgKpiScore}%. An extension of 30-45 days is recommended to validate edge-case stability and resolve remaining open risks prior to full procurement.`;
  } else {
    recommendedDecision = 'STOP';
    confidenceScore = 78;
    summaryReasoning = `Pilot has not met critical performance thresholds (KPI achievement: ${avgKpiScore}%). High operational/technical risk exposure. Recommended to conclude pilot without procurement.`;
  }

  return {
    pilot_id: pilotId,
    recommendation: recommendedDecision,
    confidence_score: confidenceScore,
    performance_breakdown: {
      kpi_achievement_score: avgKpiScore,
      milestone_delivery_score: milestoneScore,
      evidence_verification_count: verifiedEvidence,
      active_critical_risks: criticalRisks
    },
    reasoning: summaryReasoning,
    suggested_scale_parameters: recommendedDecision === 'SCALE' ? {
      recommended_target_districts: 5,
      estimated_scale_budget_inr: 2500000,
      implementation_timeline_months: 6,
      required_integrations: ['State Health Data Portal', 'District Command Center']
    } : null,
    ai_metadata: {
      model: 'SetuGov-Pilot-Evaluator-Engine',
      mode: 'mock',
      notice: 'AI recommendation is an advisory input. Final decision must be made by authorized Government officials.'
    }
  };
};

export default {
  generateChallenge,
  analyzeChallenge,
  analyzePilot
};
